server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: book-user
          uri: lb://book-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: book-book
          uri: lb://book-book
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=1
        - id: book-record
          uri: lb://book-record
          predicates:
            - Path=/api/record/**
          filters:
            - StripPrefix=1
        - id: book-recommend
          uri: lb://book-recommend
          predicates:
            - Path=/api/recommend/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: book-system-secret-key-must-be-at-least-256-bits-long-for-hs256
