-- Real demo seed data for the book system
-- User avatars come from DiceBear HTTP API
-- Book covers come from Open Library Covers API

USE `book`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Clear old data
DELETE FROM `t_reading_record`;
DELETE FROM `t_book`;
DELETE FROM `t_user`;

ALTER TABLE `t_reading_record` AUTO_INCREMENT = 1;
ALTER TABLE `t_book` AUTO_INCREMENT = 1;
ALTER TABLE `t_user` AUTO_INCREMENT = 1;

-- User data
INSERT INTO `t_user` (`id`, `username`, `password`, `nickname`, `avatar_url`, `role`, `status`) VALUES
(1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 'Admin', 'https://api.dicebear.com/9.x/adventurer/svg?seed=admin', 1, 1),
(2, 'reader01', 'e10adc3949ba59abbe56e057f20f883e', 'Reader01', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader01', 0, 1),
(3, 'reader02', 'e10adc3949ba59abbe56e057f20f883e', 'Reader02', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader02', 0, 1),
(4, 'reader03', 'e10adc3949ba59abbe56e057f20f883e', 'Reader03', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader03', 0, 1),
(5, 'reader04', 'e10adc3949ba59abbe56e057f20f883e', 'Reader04', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader04', 0, 1),
(6, 'reader05', 'e10adc3949ba59abbe56e057f20f883e', 'Reader05', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader05', 0, 1),
(7, 'reader06', 'e10adc3949ba59abbe56e057f20f883e', 'Reader06', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader06', 0, 1),
(8, 'reader07', 'e10adc3949ba59abbe56e057f20f883e', 'Reader07', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader07', 0, 1),
(9, 'reader08', 'e10adc3949ba59abbe56e057f20f883e', 'Reader08', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader08', 0, 1),
(10, 'reader09', 'e10adc3949ba59abbe56e057f20f883e', 'Reader09', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader09', 0, 1),
(11, 'reader10', 'e10adc3949ba59abbe56e057f20f883e', 'Reader10', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader10', 0, 1),
(12, 'reader11', 'e10adc3949ba59abbe56e057f20f883e', 'Reader11', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader11', 0, 1),
(13, 'reader12', 'e10adc3949ba59abbe56e057f20f883e', 'Reader12', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader12', 0, 1),
(14, 'reader13', 'e10adc3949ba59abbe56e057f20f883e', 'Reader13', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader13', 0, 1),
(15, 'reader14', 'e10adc3949ba59abbe56e057f20f883e', 'Reader14', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader14', 0, 1),
(16, 'reader15', 'e10adc3949ba59abbe56e057f20f883e', 'Reader15', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader15', 0, 1),
(17, 'reader16', 'e10adc3949ba59abbe56e057f20f883e', 'Reader16', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader16', 0, 1),
(18, 'reader17', 'e10adc3949ba59abbe56e057f20f883e', 'Reader17', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader17', 0, 1),
(19, 'reader18', 'e10adc3949ba59abbe56e057f20f883e', 'Reader18', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader18', 0, 1),
(20, 'reader19', 'e10adc3949ba59abbe56e057f20f883e', 'Reader19', 'https://api.dicebear.com/9.x/adventurer/svg?seed=reader19', 0, 1);

-- Book data
INSERT INTO `t_book` (`id`, `title`, `author`, `cover_url`, `description`, `category`, `publish_year`, `status`, `read_count`) VALUES
(1, 'Exercitia spiritualia', 'Saint Ignatius of Loyola', 'https://covers.openlibrary.org/b/id/8027976-L.jpg', 'Imported from Open Library: Exercitia spiritualia by Saint Ignatius of Loyola.', 'OpenLibrary Featured', 1548, 1, 337),
(2, 'Sonnenfinsternis', 'Arthur Koestler', 'https://covers.openlibrary.org/b/id/368797-L.jpg', 'Imported from Open Library: Sonnenfinsternis by Arthur Koestler.', 'OpenLibrary Classics', 1940, 1, 374),
(3, 'The science of getting rich, or, financial success through creative thought', 'Wallace D. Wattles', 'https://covers.openlibrary.org/b/id/854989-L.jpg', 'Imported from Open Library: The science of getting rich, or, financial success through creative thought by Wallace D. Wattles.', 'OpenLibrary Science', 1910, 1, 411),
(4, 'The Good Earth', 'Pearl S. Buck', 'https://covers.openlibrary.org/b/id/2626823-L.jpg', 'Imported from Open Library: The Good Earth by Pearl S. Buck.', 'OpenLibrary Fiction', 1931, 1, 448),
(5, 'The Voyage of the Dawn Treader', 'C. S. Lewis', 'https://covers.openlibrary.org/b/id/9184719-L.jpg', 'Imported from Open Library: The Voyage of the Dawn Treader by C. S. Lewis.', 'OpenLibrary Humanities', 1952, 1, 485),
(6, 'The Story of Philosophy', 'Will Durant', 'https://covers.openlibrary.org/b/id/405360-L.jpg', 'Imported from Open Library: The Story of Philosophy by Will Durant.', 'OpenLibrary Computing', 1926, 1, 522),
(7, 'Guess How Much I Love You', 'Sam McBratney', 'https://covers.openlibrary.org/b/id/13282906-L.jpg', 'Imported from Open Library: Guess How Much I Love You by Sam McBratney.', 'OpenLibrary Ideas', 1994, 1, 559),
(8, 'The Thirty-Nine Steps', 'John Buchan', 'https://covers.openlibrary.org/b/id/93020-L.jpg', 'Imported from Open Library: The Thirty-Nine Steps by John Buchan.', 'OpenLibrary Popular', 1915, 1, 596),
(9, 'The Boy in the Striped Pyjamas', 'John Boyne', 'https://covers.openlibrary.org/b/id/12720687-L.jpg', 'Imported from Open Library: The Boy in the Striped Pyjamas by John Boyne.', 'OpenLibrary Featured', 2006, 1, 633),
(10, 'The Hunger Games', 'Suzanne Collins', 'https://covers.openlibrary.org/b/id/12646537-L.jpg', 'Imported from Open Library: The Hunger Games by Suzanne Collins.', 'OpenLibrary Classics', 2008, 1, 670),
(11, 'Le Comte de Monte Cristo', 'Alexandre Dumas', 'https://covers.openlibrary.org/b/id/14566393-L.jpg', 'Imported from Open Library: Le Comte de Monte Cristo by Alexandre Dumas.', 'OpenLibrary Science', 1830, 1, 707),
(12, 'Uncle Tom''s Cabin', 'Harriet Beecher Stowe', 'https://covers.openlibrary.org/b/id/12728198-L.jpg', 'Imported from Open Library: Uncle Tom''''s Cabin by Harriet Beecher Stowe.', 'OpenLibrary Fiction', 1850, 1, 744),
(13, 'Adventures of Huckleberry Finn', 'Mark Twain', 'https://covers.openlibrary.org/b/id/8157718-L.jpg', 'Imported from Open Library: Adventures of Huckleberry Finn by Mark Twain.', 'OpenLibrary Humanities', 1876, 1, 781),
(14, 'NASA/DoD aerospace knowledge diffusion research project', 'Thomas E. Pinelli', 'https://covers.openlibrary.org/b/id/8936636-L.jpg', 'Imported from Open Library: NASA/DoD aerospace knowledge diffusion research project by Thomas E. Pinelli.', 'OpenLibrary Computing', 1990, 1, 818),
(15, 'Catching Fire', 'Suzanne Collins', 'https://covers.openlibrary.org/b/id/12646539-L.jpg', 'Imported from Open Library: Catching Fire by Suzanne Collins.', 'OpenLibrary Ideas', 2009, 1, 855),
(16, 'Gulliver''s Travels', 'Jonathan Swift', 'https://covers.openlibrary.org/b/id/12717083-L.jpg', 'Imported from Open Library: Gulliver''''s Travels by Jonathan Swift.', 'OpenLibrary Popular', 1726, 1, 892),
(17, 'King Lear', 'William Shakespeare', 'https://covers.openlibrary.org/b/id/7420452-L.jpg', 'Imported from Open Library: King Lear by William Shakespeare.', 'OpenLibrary Featured', 1608, 1, 929),
(18, 'Principles of Anatomy and Physiology', 'Gerard J. Tortora', 'https://covers.openlibrary.org/b/id/3810109-L.jpg', 'Imported from Open Library: Principles of Anatomy and Physiology by Gerard J. Tortora.', 'OpenLibrary Classics', 1975, 1, 966),
(19, 'Autobiography of a Yogi', 'Yogananda Paramahansa', 'https://covers.openlibrary.org/b/id/805448-L.jpg', 'Imported from Open Library: Autobiography of a Yogi by Yogananda Paramahansa.', 'OpenLibrary Science', 1946, 1, 1003),
(20, 'Hamlet', 'William Shakespeare', 'https://covers.openlibrary.org/b/id/8281954-L.jpg', 'Imported from Open Library: Hamlet by William Shakespeare.', 'OpenLibrary Fiction', 1603, 1, 1040),
(21, 'The Alchemist, 1612', 'Ben Jonson', 'https://covers.openlibrary.org/b/id/7463992-L.jpg', 'Imported from Open Library: The Alchemist, 1612 by Ben Jonson.', 'OpenLibrary Humanities', 1612, 1, 1077),
(22, 'The Ugly Duckling', 'Hans Christian Andersen', 'https://covers.openlibrary.org/b/id/446546-L.jpg', 'Imported from Open Library: The Ugly Duckling by Hans Christian Andersen.', 'OpenLibrary Computing', 1851, 1, 1114),
(23, 'Of Mice and Men', 'John Steinbeck', 'https://covers.openlibrary.org/b/id/14319003-L.jpg', 'Imported from Open Library: Of Mice and Men by John Steinbeck.', 'OpenLibrary Ideas', 1937, 1, 1151),
(24, 'Software Engineering', 'Roger S. Pressman', 'https://covers.openlibrary.org/b/id/66176-L.jpg', 'Imported from Open Library: Software Engineering by Roger S. Pressman.', 'OpenLibrary Popular', 1982, 1, 1188),
(25, 'Software engineering', 'Shari Lawrence Pfleeger', 'https://covers.openlibrary.org/b/id/82245-L.jpg', 'Imported from Open Library: Software engineering by Shari Lawrence Pfleeger.', 'OpenLibrary Featured', 1987, 1, 1225),
(26, 'Software engineering', 'Ian Sommerville', 'https://covers.openlibrary.org/b/id/3973371-L.jpg', 'Imported from Open Library: Software engineering by Ian Sommerville.', 'OpenLibrary Classics', 1982, 1, 1262),
(27, 'The Mythical Man-Month', 'Frederick P. Brooks', 'https://covers.openlibrary.org/b/id/6915361-L.jpg', 'Imported from Open Library: The Mythical Man-Month by Frederick P. Brooks.', 'OpenLibrary Science', 1975, 1, 1299),
(28, 'Object-Oriented Software Engineering', 'Ivar Jacobson', 'https://covers.openlibrary.org/b/id/135140-L.jpg', 'Imported from Open Library: Object-Oriented Software Engineering by Ivar Jacobson.', 'OpenLibrary Fiction', 1992, 1, 1336),
(29, 'Introduction to software engineering', 'Ronald J. Leach', 'https://covers.openlibrary.org/b/id/1595411-L.jpg', 'Imported from Open Library: Introduction to software engineering by Ronald J. Leach.', 'OpenLibrary Humanities', 2000, 1, 1373),
(30, 'Software Engineering', 'Eric J. Braude', 'https://covers.openlibrary.org/b/id/5361897-L.jpg', 'Imported from Open Library: Software Engineering by Eric J. Braude.', 'OpenLibrary Computing', 2000, 1, 1410),
(31, 'Managing Humans', 'Michael Lopp', 'https://covers.openlibrary.org/b/id/8363540-L.jpg', 'Imported from Open Library: Managing Humans by Michael Lopp.', 'OpenLibrary Ideas', 2007, 1, 1447),
(32, 'Software engineering', 'Randall W. Jensen', 'https://covers.openlibrary.org/b/id/11768067-L.jpg', 'Imported from Open Library: Software engineering by Randall W. Jensen.', 'OpenLibrary Popular', 1979, 1, 1484),
(33, 'Classical and object-oriented software engineering', 'Stephen R. Schach', 'https://covers.openlibrary.org/b/id/3888779-L.jpg', 'Imported from Open Library: Classical and object-oriented software engineering by Stephen R. Schach.', 'OpenLibrary Featured', 1996, 1, 1521),
(34, 'Software engineering', 'Philip Sallis', 'https://covers.openlibrary.org/b/id/11015287-L.jpg', 'Imported from Open Library: Software engineering by Philip Sallis.', 'OpenLibrary Classics', 1995, 1, 1558),
(35, 'Fundamentals of Software Engineering', 'Rajib Mall', 'https://covers.openlibrary.org/b/id/4884220-L.jpg', 'Imported from Open Library: Fundamentals of Software Engineering by Rajib Mall.', 'OpenLibrary Science', 2004, 1, 1595),
(36, 'Advances in Computers, Volume 49 (Advances in Computers)', 'Marvin V. Zelkowitz', 'https://covers.openlibrary.org/b/id/1094406-L.jpg', 'Imported from Open Library: Advances in Computers, Volume 49 (Advances in Computers) by Marvin V. Zelkowitz.', 'OpenLibrary Fiction', 1995, 1, 1632),
(37, 'Software engineering', 'Ian Somerville', 'https://covers.openlibrary.org/b/id/14653545-L.jpg', 'Imported from Open Library: Software engineering by Ian Somerville.', 'OpenLibrary Humanities', 2002, 1, 1669),
(38, 'Software engineering', 'Marc Thorin', 'https://covers.openlibrary.org/b/id/4193793-L.jpg', 'Imported from Open Library: Software engineering by Marc Thorin.', 'OpenLibrary Computing', 1985, 1, 1706),
(39, 'Software engineering environments', 'Ian Sommerville', 'https://covers.openlibrary.org/b/id/12512115-L.jpg', 'Imported from Open Library: Software engineering environments by Ian Sommerville.', 'OpenLibrary Ideas', 1986, 1, 1743),
(40, 'The Marvelous Land of Oz', 'L. Frank Baum', 'https://covers.openlibrary.org/b/id/12648656-L.jpg', 'Imported from Open Library: The Marvelous Land of Oz by L. Frank Baum.', 'OpenLibrary Popular', 1904, 1, 1780),
(41, 'The Wonderful Wizard of Oz', 'L. Frank Baum', 'https://covers.openlibrary.org/b/id/552443-L.jpg', 'Imported from Open Library: The Wonderful Wizard of Oz by L. Frank Baum.', 'OpenLibrary Featured', 1899, 1, 1817),
(42, 'Alice''s Adventures in Wonderland', 'Lewis Carroll', 'https://covers.openlibrary.org/b/id/10527843-L.jpg', 'Imported from Open Library: Alice''''s Adventures in Wonderland by Lewis Carroll.', 'OpenLibrary Classics', 1865, 1, 1854),
(43, 'Pride and Prejudice', 'Jane Austen', 'https://covers.openlibrary.org/b/id/14348537-L.jpg', 'Imported from Open Library: Pride and Prejudice by Jane Austen.', 'OpenLibrary Science', 1813, 1, 1891),
(44, 'Don Quijote de la Mancha', 'Miguel de Cervantes Saavedra', 'https://covers.openlibrary.org/b/id/14428305-L.jpg', 'Imported from Open Library: Don Quijote de la Mancha by Miguel de Cervantes Saavedra.', 'OpenLibrary Fiction', 1600, 1, 1928),
(45, 'Software engineering', 'Allen Macro', 'https://covers.openlibrary.org/b/id/4089805-L.jpg', 'Imported from Open Library: Software engineering by Allen Macro.', 'OpenLibrary Humanities', 1990, 1, 1965),
(46, 'Fundamentals of software engineering', 'Carlo Ghezzi', 'https://covers.openlibrary.org/b/id/92131-L.jpg', 'Imported from Open Library: Fundamentals of software engineering by Carlo Ghezzi.', 'OpenLibrary Computing', 1991, 1, 2002),
(47, 'Software engineering', 'M. Dorfman', 'https://covers.openlibrary.org/b/id/617428-L.jpg', 'Imported from Open Library: Software engineering by M. Dorfman.', 'OpenLibrary Ideas', 1996, 1, 2039),
(48, 'Introduction to Algorithms', 'Thomas H. Cormen', 'https://covers.openlibrary.org/b/id/2341462-L.jpg', 'Imported from Open Library: Introduction to Algorithms by Thomas H. Cormen.', 'OpenLibrary Popular', 1990, 1, 2076),
(49, 'Prey', 'Michael Crichton', 'https://covers.openlibrary.org/b/id/10984324-L.jpg', 'Imported from Open Library: Prey by Michael Crichton.', 'OpenLibrary Featured', 2002, 1, 2113),
(50, 'Algorithms to Live By', 'Brian Christian', 'https://covers.openlibrary.org/b/id/8042539-L.jpg', 'Imported from Open Library: Algorithms to Live By by Brian Christian.', 'OpenLibrary Classics', 2016, 1, 2150),
(51, 'Data Structures and Algorithms Made Easy', 'Narasimha Karumanchi', 'https://covers.openlibrary.org/b/id/11067110-L.jpg', 'Imported from Open Library: Data Structures and Algorithms Made Easy by Narasimha Karumanchi.', 'OpenLibrary Science', 2011, 1, 2187),
(52, 'Computer Networks', 'Andrew S. Tanenbaum', 'https://covers.openlibrary.org/b/id/9378629-L.jpg', 'Imported from Open Library: Computer Networks by Andrew S. Tanenbaum.', 'OpenLibrary Fiction', 1981, 1, 2224),
(53, 'The Emperor''s New Mind', 'Roger Penrose', 'https://covers.openlibrary.org/b/id/7901942-L.jpg', 'Imported from Open Library: The Emperor''''s New Mind by Roger Penrose.', 'OpenLibrary Humanities', 1989, 1, 2261),
(54, 'Artificial intelligence', 'Stuart J. Russell', 'https://covers.openlibrary.org/b/id/92018-L.jpg', 'Imported from Open Library: Artificial intelligence by Stuart J. Russell.', 'OpenLibrary Computing', 1994, 1, 2298),
(55, 'The art of computer programming', 'Donald Knuth', 'https://covers.openlibrary.org/b/id/136600-L.jpg', 'Imported from Open Library: The art of computer programming by Donald Knuth.', 'OpenLibrary Ideas', 1968, 1, 2335),
(56, 'Modern Operating Systems', 'Andrew S. Tanenbaum', 'https://covers.openlibrary.org/b/id/9378721-L.jpg', 'Imported from Open Library: Modern Operating Systems by Andrew S. Tanenbaum.', 'OpenLibrary Popular', 1992, 1, 2372),
(57, 'Digital signal processing', 'John G. Proakis', 'https://covers.openlibrary.org/b/id/1113539-L.jpg', 'Imported from Open Library: Digital signal processing by John G. Proakis.', 'OpenLibrary Featured', 1992, 1, 2409),
(58, 'Data structures and algorithms', 'Alfred V. Aho', 'https://covers.openlibrary.org/b/id/134008-L.jpg', 'Imported from Open Library: Data structures and algorithms by Alfred V. Aho.', 'OpenLibrary Classics', 1983, 1, 2446),
(59, 'Computer networking', 'James F. Kurose', 'https://covers.openlibrary.org/b/id/193126-L.jpg', 'Imported from Open Library: Computer networking by James F. Kurose.', 'OpenLibrary Science', 1900, 1, 2483),
(60, 'Grokking Algorithms: An illustrated guide for programmers and other curious people', 'Aditya Y. Bhargava', 'https://covers.openlibrary.org/b/id/8512926-L.jpg', 'Imported from Open Library: Grokking Algorithms: An illustrated guide for programmers and other curious people by Aditya Y. Bhargava.', 'OpenLibrary Fiction', 2016, 1, 2520),
(61, 'The algorithm design manual', 'Steven S. Skiena', 'https://covers.openlibrary.org/b/id/245565-L.jpg', 'Imported from Open Library: The algorithm design manual by Steven S. Skiena.', 'OpenLibrary Humanities', 1998, 1, 2557),
(62, 'Computer science', 'J. Glenn Brookshear', 'https://covers.openlibrary.org/b/id/193281-L.jpg', 'Imported from Open Library: Computer science by J. Glenn Brookshear.', 'OpenLibrary Computing', 1985, 1, 2594),
(63, 'Discrete Mathematics and Its Applications', 'Kenneth H. Rosen', 'https://covers.openlibrary.org/b/id/7083171-L.jpg', 'Imported from Open Library: Discrete Mathematics and Its Applications by Kenneth H. Rosen.', 'OpenLibrary Ideas', 1988, 1, 2631),
(64, 'Mathematical structures for computer science', 'Judith L. Gersting', 'https://covers.openlibrary.org/b/id/7136779-L.jpg', 'Imported from Open Library: Mathematical structures for computer science by Judith L. Gersting.', 'OpenLibrary Popular', 1982, 1, 2668),
(65, 'Invitation to Computer Science', 'G. Michael Schneider', 'https://covers.openlibrary.org/b/id/8524066-L.jpg', 'Imported from Open Library: Invitation to Computer Science by G. Michael Schneider.', 'OpenLibrary Featured', 1995, 1, 2705),
(66, 'Weapons of Math Destruction', 'Cathy O''Neil', 'https://covers.openlibrary.org/b/id/8136557-L.jpg', 'Imported from Open Library: Weapons of Math Destruction by Cathy O''''Neil.', 'OpenLibrary Classics', 2016, 1, 2742),
(67, 'JavaScript', 'David Flanagan', 'https://covers.openlibrary.org/b/id/10737959-L.jpg', 'Imported from Open Library: JavaScript by David Flanagan.', 'OpenLibrary Science', 1996, 1, 2779),
(68, 'Hello world', 'Hannah Fry', 'https://covers.openlibrary.org/b/id/10567981-L.jpg', 'Imported from Open Library: Hello world by Hannah Fry.', 'OpenLibrary Fiction', 2018, 1, 2816),
(69, 'Hacking', 'Jon Erickson', 'https://covers.openlibrary.org/b/id/1984286-L.jpg', 'Imported from Open Library: Hacking by Jon Erickson.', 'OpenLibrary Humanities', 2003, 1, 2853),
(70, 'Data Communications and Networking', 'Behrouz A. Forouzan', 'https://covers.openlibrary.org/b/id/1084050-L.jpg', 'Imported from Open Library: Data Communications and Networking by Behrouz A. Forouzan.', 'OpenLibrary Computing', 2000, 1, 2890),
(71, 'Algorithms of Oppression', 'Safiya Umoja Noble', 'https://covers.openlibrary.org/b/id/12856940-L.jpg', 'Imported from Open Library: Algorithms of Oppression by Safiya Umoja Noble.', 'OpenLibrary Ideas', 2018, 1, 2927),
(72, 'Data structures and algorithm analysis in C', 'Mark Allen Weiss', 'https://covers.openlibrary.org/b/id/193887-L.jpg', 'Imported from Open Library: Data structures and algorithm analysis in C by Mark Allen Weiss.', 'OpenLibrary Popular', 1993, 1, 2964),
(73, 'The Master Algorithm', 'Pedro Domingos', 'https://covers.openlibrary.org/b/id/9321915-L.jpg', 'Imported from Open Library: The Master Algorithm by Pedro Domingos.', 'OpenLibrary Featured', 2015, 1, 3001),
(74, 'Introduction to automata theory, languages, and computation', 'John E. Hopcroft', 'https://covers.openlibrary.org/b/id/134856-L.jpg', 'Imported from Open Library: Introduction to automata theory, languages, and computation by John E. Hopcroft.', 'OpenLibrary Classics', 1979, 1, 3038),
(75, 'Advances in Computers', 'Marshall C. Yovits', 'https://covers.openlibrary.org/b/id/9297074-L.jpg', 'Imported from Open Library: Advances in Computers by Marshall C. Yovits.', 'OpenLibrary Science', 1971, 1, 3075),
(76, 'Applied Cryptography', 'Bruce Schneier', 'https://covers.openlibrary.org/b/id/3930979-L.jpg', 'Imported from Open Library: Applied Cryptography by Bruce Schneier.', 'OpenLibrary Fiction', 1994, 1, 3112),
(77, 'Computer system architecture', 'M. Morris Mano', 'https://covers.openlibrary.org/b/id/10192526-L.jpg', 'Imported from Open Library: Computer system architecture by M. Morris Mano.', 'OpenLibrary Humanities', 1983, 1, 3149),
(78, 'The Autobiography of Benjamin Franklin', 'Benjamin Franklin', 'https://covers.openlibrary.org/b/id/5647361-L.jpg', 'Imported from Open Library: The Autobiography of Benjamin Franklin by Benjamin Franklin.', 'OpenLibrary Computing', 1791, 1, 3186),
(79, 'A Christmas Carol', 'Charles Dickens', 'https://covers.openlibrary.org/b/id/12875748-L.jpg', 'Imported from Open Library: A Christmas Carol by Charles Dickens.', 'OpenLibrary Ideas', 1843, 1, 3223),
(80, 'Computer systems', 'Randal Bryant', 'https://covers.openlibrary.org/b/id/12475555-L.jpg', 'Imported from Open Library: Computer systems by Randal Bryant.', 'OpenLibrary Popular', 2002, 1, 3260),
(81, 'Computer systems', 'J. Stanley Warford', 'https://covers.openlibrary.org/b/id/3727821-L.jpg', 'Imported from Open Library: Computer systems by J. Stanley Warford.', 'OpenLibrary Featured', 1998, 1, 3297),
(82, 'Linear algebra and its applications', 'David C. Lay', 'https://covers.openlibrary.org/b/id/13054058-L.jpg', 'Imported from Open Library: Linear algebra and its applications by David C. Lay.', 'OpenLibrary Classics', 1994, 1, 3334),
(83, 'Computer systems design and architecture', 'Vincent P. Heuring', 'https://covers.openlibrary.org/b/id/83497-L.jpg', 'Imported from Open Library: Computer systems design and architecture by Vincent P. Heuring.', 'OpenLibrary Science', 1997, 1, 3371),
(84, 'Player Piano', 'Kurt Vonnegut', 'https://covers.openlibrary.org/b/id/280246-L.jpg', 'Imported from Open Library: Player Piano by Kurt Vonnegut.', 'OpenLibrary Fiction', 1952, 1, 3408),
(85, 'Understanding computer systems', 'Harold W. Lawson', 'https://covers.openlibrary.org/b/id/6888582-L.jpg', 'Imported from Open Library: Understanding computer systems by Harold W. Lawson.', 'OpenLibrary Humanities', 1979, 1, 3445),
(86, 'Neuromancer', 'William Gibson', 'https://covers.openlibrary.org/b/id/283860-L.jpg', 'Imported from Open Library: Neuromancer by William Gibson.', 'OpenLibrary Computing', 1984, 1, 3482),
(87, 'Operating systems', 'Stuart E. Madnick', 'https://covers.openlibrary.org/b/id/4466229-L.jpg', 'Imported from Open Library: Operating systems by Stuart E. Madnick.', 'OpenLibrary Ideas', 1974, 1, 3519),
(88, 'Computer programming and computer systems', 'Anthony Hassitt', 'https://covers.openlibrary.org/b/id/10991748-L.jpg', 'Imported from Open Library: Computer programming and computer systems by Anthony Hassitt.', 'OpenLibrary Popular', 1967, 1, 3556),
(89, 'Systems Analysis and Design', 'Alan Dennis', 'https://covers.openlibrary.org/b/id/304506-L.jpg', 'Imported from Open Library: Systems Analysis and Design by Alan Dennis.', 'OpenLibrary Featured', 2000, 1, 3593),
(90, 'Programming real-time computer systems', 'James Martin', 'https://covers.openlibrary.org/b/id/9742371-L.jpg', 'Imported from Open Library: Programming real-time computer systems by James Martin.', 'OpenLibrary Classics', 1965, 1, 3630),
(91, 'Introducing Computers', 'Robert H. Blissmer', 'https://covers.openlibrary.org/b/id/4642108-L.jpg', 'Imported from Open Library: Introducing Computers by Robert H. Blissmer.', 'OpenLibrary Science', 1988, 1, 3667),
(92, 'Computer systems architecture', 'Robert M. Newman', 'https://covers.openlibrary.org/b/id/11608678-L.jpg', 'Imported from Open Library: Computer systems architecture by Robert M. Newman.', 'OpenLibrary Fiction', 2005, 1, 3704),
(93, 'Computing systems reliability', 'Anderson, Tom', 'https://covers.openlibrary.org/b/id/4657549-L.jpg', 'Imported from Open Library: Computing systems reliability by Anderson, Tom.', 'OpenLibrary Humanities', 1979, 1, 3741),
(94, 'Operating System Concepts', 'Abraham Silberschatz', 'https://covers.openlibrary.org/b/id/302591-L.jpg', 'Imported from Open Library: Operating System Concepts by Abraham Silberschatz.', 'OpenLibrary Computing', 1988, 1, 3778),
(95, 'Artificial intelligence', 'Patrick Henry Winston', 'https://covers.openlibrary.org/b/id/135105-L.jpg', 'Imported from Open Library: Artificial intelligence by Patrick Henry Winston.', 'OpenLibrary Ideas', 1977, 1, 3815),
(96, 'Artificial intelligence', 'Elaine A. Rich', 'https://covers.openlibrary.org/b/id/55159-L.jpg', 'Imported from Open Library: Artificial intelligence by Elaine A. Rich.', 'OpenLibrary Popular', 1983, 1, 3852),
(97, 'Artificial Intelligence and Intelligent Systems', 'N. P. Padhy', 'https://covers.openlibrary.org/b/id/128294-L.jpg', 'Imported from Open Library: Artificial Intelligence and Intelligent Systems by N. P. Padhy.', 'OpenLibrary Featured', 2005, 1, 3889),
(98, 'Artificial Intelligence and Soft Computing', 'Leszek Rutkowski', 'https://covers.openlibrary.org/b/id/8619487-L.jpg', 'Imported from Open Library: Artificial Intelligence and Soft Computing by Leszek Rutkowski.', 'OpenLibrary Classics', 2012, 1, 3926),
(99, 'Understanding Artificial Intelligence', 'Henry C. Mishkoff', 'https://covers.openlibrary.org/b/id/6572294-L.jpg', 'Imported from Open Library: Understanding Artificial Intelligence by Henry C. Mishkoff.', 'OpenLibrary Science', 1985, 1, 3963),
(100, 'Artificial Intelligence', 'Melanie Mitchell', 'https://covers.openlibrary.org/b/id/9333846-L.jpg', 'Imported from Open Library: Artificial Intelligence by Melanie Mitchell.', 'OpenLibrary Fiction', 2019, 1, 4000);

-- Reading record data
INSERT INTO `t_reading_record` (`id`, `user_id`, `book_id`, `book_title`, `book_cover`, `read_status`) VALUES
(1, 2, 1, 'Exercitia spiritualia', 'https://covers.openlibrary.org/b/id/8027976-L.jpg', 0),
(2, 2, 2, 'Sonnenfinsternis', 'https://covers.openlibrary.org/b/id/368797-L.jpg', 1),
(3, 2, 3, 'The science of getting rich, or, financial success through creative thought', 'https://covers.openlibrary.org/b/id/854989-L.jpg', 0),
(4, 3, 4, 'The Good Earth', 'https://covers.openlibrary.org/b/id/2626823-L.jpg', 1),
(5, 3, 5, 'The Voyage of the Dawn Treader', 'https://covers.openlibrary.org/b/id/9184719-L.jpg', 0),
(6, 3, 6, 'The Story of Philosophy', 'https://covers.openlibrary.org/b/id/405360-L.jpg', 1),
(7, 4, 7, 'Guess How Much I Love You', 'https://covers.openlibrary.org/b/id/13282906-L.jpg', 0),
(8, 4, 8, 'The Thirty-Nine Steps', 'https://covers.openlibrary.org/b/id/93020-L.jpg', 1),
(9, 4, 9, 'The Boy in the Striped Pyjamas', 'https://covers.openlibrary.org/b/id/12720687-L.jpg', 0),
(10, 5, 10, 'The Hunger Games', 'https://covers.openlibrary.org/b/id/12646537-L.jpg', 1),
(11, 5, 11, 'Le Comte de Monte Cristo', 'https://covers.openlibrary.org/b/id/14566393-L.jpg', 0),
(12, 5, 12, 'Uncle Tom''s Cabin', 'https://covers.openlibrary.org/b/id/12728198-L.jpg', 1),
(13, 6, 13, 'Adventures of Huckleberry Finn', 'https://covers.openlibrary.org/b/id/8157718-L.jpg', 0),
(14, 6, 14, 'NASA/DoD aerospace knowledge diffusion research project', 'https://covers.openlibrary.org/b/id/8936636-L.jpg', 1),
(15, 6, 15, 'Catching Fire', 'https://covers.openlibrary.org/b/id/12646539-L.jpg', 0),
(16, 7, 16, 'Gulliver''s Travels', 'https://covers.openlibrary.org/b/id/12717083-L.jpg', 1),
(17, 7, 17, 'King Lear', 'https://covers.openlibrary.org/b/id/7420452-L.jpg', 0),
(18, 7, 18, 'Principles of Anatomy and Physiology', 'https://covers.openlibrary.org/b/id/3810109-L.jpg', 1),
(19, 8, 19, 'Autobiography of a Yogi', 'https://covers.openlibrary.org/b/id/805448-L.jpg', 0),
(20, 8, 20, 'Hamlet', 'https://covers.openlibrary.org/b/id/8281954-L.jpg', 1),
(21, 8, 21, 'The Alchemist, 1612', 'https://covers.openlibrary.org/b/id/7463992-L.jpg', 0),
(22, 9, 22, 'The Ugly Duckling', 'https://covers.openlibrary.org/b/id/446546-L.jpg', 1),
(23, 9, 23, 'Of Mice and Men', 'https://covers.openlibrary.org/b/id/14319003-L.jpg', 0),
(24, 9, 24, 'Software Engineering', 'https://covers.openlibrary.org/b/id/66176-L.jpg', 1),
(25, 10, 25, 'Software engineering', 'https://covers.openlibrary.org/b/id/82245-L.jpg', 0),
(26, 10, 26, 'Software engineering', 'https://covers.openlibrary.org/b/id/3973371-L.jpg', 1),
(27, 10, 27, 'The Mythical Man-Month', 'https://covers.openlibrary.org/b/id/6915361-L.jpg', 0),
(28, 11, 28, 'Object-Oriented Software Engineering', 'https://covers.openlibrary.org/b/id/135140-L.jpg', 1),
(29, 11, 29, 'Introduction to software engineering', 'https://covers.openlibrary.org/b/id/1595411-L.jpg', 0),
(30, 11, 30, 'Software Engineering', 'https://covers.openlibrary.org/b/id/5361897-L.jpg', 1),
(31, 12, 31, 'Managing Humans', 'https://covers.openlibrary.org/b/id/8363540-L.jpg', 0),
(32, 12, 32, 'Software engineering', 'https://covers.openlibrary.org/b/id/11768067-L.jpg', 1),
(33, 12, 33, 'Classical and object-oriented software engineering', 'https://covers.openlibrary.org/b/id/3888779-L.jpg', 0),
(34, 13, 34, 'Software engineering', 'https://covers.openlibrary.org/b/id/11015287-L.jpg', 1),
(35, 13, 35, 'Fundamentals of Software Engineering', 'https://covers.openlibrary.org/b/id/4884220-L.jpg', 0),
(36, 13, 36, 'Advances in Computers, Volume 49 (Advances in Computers)', 'https://covers.openlibrary.org/b/id/1094406-L.jpg', 1),
(37, 14, 37, 'Software engineering', 'https://covers.openlibrary.org/b/id/14653545-L.jpg', 0),
(38, 14, 38, 'Software engineering', 'https://covers.openlibrary.org/b/id/4193793-L.jpg', 1),
(39, 14, 39, 'Software engineering environments', 'https://covers.openlibrary.org/b/id/12512115-L.jpg', 0),
(40, 15, 40, 'The Marvelous Land of Oz', 'https://covers.openlibrary.org/b/id/12648656-L.jpg', 1),
(41, 15, 41, 'The Wonderful Wizard of Oz', 'https://covers.openlibrary.org/b/id/552443-L.jpg', 0),
(42, 15, 42, 'Alice''s Adventures in Wonderland', 'https://covers.openlibrary.org/b/id/10527843-L.jpg', 1),
(43, 16, 43, 'Pride and Prejudice', 'https://covers.openlibrary.org/b/id/14348537-L.jpg', 0),
(44, 16, 44, 'Don Quijote de la Mancha', 'https://covers.openlibrary.org/b/id/14428305-L.jpg', 1),
(45, 16, 45, 'Software engineering', 'https://covers.openlibrary.org/b/id/4089805-L.jpg', 0),
(46, 17, 46, 'Fundamentals of software engineering', 'https://covers.openlibrary.org/b/id/92131-L.jpg', 1),
(47, 17, 47, 'Software engineering', 'https://covers.openlibrary.org/b/id/617428-L.jpg', 0),
(48, 17, 48, 'Introduction to Algorithms', 'https://covers.openlibrary.org/b/id/2341462-L.jpg', 1),
(49, 18, 49, 'Prey', 'https://covers.openlibrary.org/b/id/10984324-L.jpg', 0),
(50, 18, 50, 'Algorithms to Live By', 'https://covers.openlibrary.org/b/id/8042539-L.jpg', 1),
(51, 18, 51, 'Data Structures and Algorithms Made Easy', 'https://covers.openlibrary.org/b/id/11067110-L.jpg', 0),
(52, 19, 52, 'Computer Networks', 'https://covers.openlibrary.org/b/id/9378629-L.jpg', 1),
(53, 19, 53, 'The Emperor''s New Mind', 'https://covers.openlibrary.org/b/id/7901942-L.jpg', 0),
(54, 19, 54, 'Artificial intelligence', 'https://covers.openlibrary.org/b/id/92018-L.jpg', 1),
(55, 20, 55, 'The art of computer programming', 'https://covers.openlibrary.org/b/id/136600-L.jpg', 0),
(56, 20, 56, 'Modern Operating Systems', 'https://covers.openlibrary.org/b/id/9378721-L.jpg', 1),
(57, 20, 57, 'Digital signal processing', 'https://covers.openlibrary.org/b/id/1113539-L.jpg', 0);

SET FOREIGN_KEY_CHECKS = 1;
